hendrixodyssey/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^odyssey/', include('projects.urls')),
    url(r'^admin/', admin.site.urls),
]

projects/urls.py
from django.conf.urls import url
from . import views

app_name = 'projects'
urlpatterns = [
          url(
               r'^office/$', 
               views.odyLanding, 
               name='odyLanding'
          ),
          url(
               r'^student/$', 
               views.landing, 
               name = 'landing'
          ),
          url(
               r'^supervisor/$', 
               views.superLanding, 
               name='superLanding'
          ),
          url(
               r'^$', 
               views.viewAs, 
               name = 'viewas'
          ),
          url(
               r'^proposal/$', 
               views.viewProposal, 
               name = 'proposal'
          ),
          url(
               r'^student/complete-project/(?P<project_id>[0-9]+)/$', 
               views.viewCompletion, 
               name = 'completion'
          ),
          url(
               r'^student/project-status/(?P<project_id>[0-9]+)',
               views.status, 
               name='status'
          ),
          url(
               r'^student/proposal/submit/', 
               views.submitProposal, 
               name='submit'
          ),
          url(
               r'^upload/$', 
               views.upload, 
               name='upload'
          ),
          url(
               r'^upload/success', 
               views.success, 
               name='success'
          ),
          url(
               r'^success', 
               views.success, 
               name='success'
          ),
          url(
               r'^student/edit-form/(?P<project_id>[0-9]+)/$',
               views.editProposal, 
               name='edit'
          ),
          url(
               r'^student/edit-form/(?P<project_id>[0-9]+)/submit',
               views.submitSavedProposal, 
               name='submitedit'
          ),
          url(
               r'^student/edit-completion-form/(?P<project_id>[0-9]+)/submit',
               views.submitSavedCompletion, 
               name='submitcompleteedit'
          ),
          url(
               r'^student/complete-project/(?P<project_id>[0-9]+)/submit',
               views.submitCompletion, 
               name='submitcompletion'
          ),
          url(
               r'^student/edit-completion-form/(?P<project_id>[0-9]+)/$',
               views.editCompletion, 
               name='editcomp'
          ),
          url(
               r'^supervisor/review-proposal/(?P<project_id>[0-9]+)/$', 
               views.reviewProposal,
               name='superprop'
          ),
          url(
               r'^supervisor/review-proposal/(?P<project_id>[0-9]+)/submit',
               views.superAppProposal, 
               name='superapp'
          ),
          url(
               r'^accounts/login/$', 
               views.loginView
          ),
          url(
               r'^accounts/login/submit/', 
               views.my_view
          ),
          url(
               r'^office/review-proposal/(?P<project_id>[0-9]+)/$', 
               views.odyReviewProposal,
               name='odyReviewProp'
          ),
          url(
               r'^office/review-proposal/(?P<project_id>[0-9]+)/submit',
               views.odyAppProposal, 
               name='odyapp' 
          ),
          url(
               r'^accounts/signup/$',
               views.signup
          ),
          url(
               r'^accounts/signup/submit',
               views.signup
          ),

          url(
               r'^office/review-proposal/(?P<project_id>[0-9]+)/$', 
               views.odyReviewProposal,
               name='odyReviewProp'
          ),
          url(
               r'^office/review-proposal/(?P<project_id>[0-9]+)/submit',
               views.odyAppProposal, 
               name='odyapp'
          ),
          url(
               r'^supervisor/project-status/(?P<project_id>[0-9]+)/$',
               views.supViewStatus, 
               name='superview'
          ),
          url(
               r'^odyssey/project-status/(?P<project_id>[0-9]+)/$',
               views.odyViewStatus, 
               name='odyview' 
          ),
          url(
               r'^odyssey/review-completion/(?P<project_id>[0-9]+)/$',
               views.odyReviewComp, 
               name='odyReviewComp'
          ),
          url(
               r'^supervisor/review-completion/(?P<project_id>[0-9]+)/$',
               views.supReviewComp, 
               name='supReviewComp'
          ),
               
     ]

projects/models.py
from django.db import models
from django.contrib.auth.models import User, Group
##should be using get_user_model()
##https://docs.djangoproject.com/en/1.9/topics/auth/customizing/#referencing-the-user-model
class Project(models.Model):
    title = models.CharField(max_length=200)
    category = models.CharField(max_length=20)
    advisor = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(max_length=60)
    start_date = models.DateField('start date')
    end_date = models.DateField('end date')
    update_date = models.DateField('updated on')
    def __str__(self):
        return self.title

class ProjectGroup(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    def __str__(self):
        return self.project.title+": "+self.student.first_name+" "+self.student.last_name
    class Meta:
        unique_together = (("student", "project"),)

def user_dir_path(instance, filename):
    return 'proposals/project_{0}/{1}'.format(instance.project_id, (filename+'%Y-%m-%d'))
    
class Proposal(models.Model):
    project_id = models.OneToOneField(Project, on_delete=models.CASCADE, primary_key=True)
    narrative = models.TextField()
    created_date = models.DateField('created on')
    status = models.CharField(max_length=60)
    updated_date = models.DateField('updated on')
    def __str__(self):
        return self.project_id.title


class Completion(models.Model):
    project_id = models.OneToOneField(Project, on_delete=models.CASCADE, primary_key=True)
    status = models.CharField(max_length=60)
    created_date = models.DateField('created on')
    updated_date = models.DateField('updated on')
    hours = models.CharField(max_length=10)
    notation = models.TextField()
    def __str__(self):
        return "Completion: " + self.project_id.title

projects/forms.py
from django import forms
from .models import Project
from django.contrib.auth.models import User


class SubmitProposal(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['title', 'category', 'advisor']
        widgets = {
            'title' : forms.TextInput(attrs={'id':'title',
                                             'required':True,
                                             'placeholder':'Title'}),
            'category' : forms.TextInput(attrs={'id':'category','required':True,
                                                'placeholder':'Category'})
            }
            
        

projects/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.http import Http404
from django.views import generic
from django.template import loader
from .models import *
from django.contrib.auth.models import User, Group
from .forms import *
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from os.path import basename
import datetime
import pypandoc
from io import *
from docx import Document
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login

import logging
logger = logging.getLogger(__name__)
categories = ['Artistic Creativity', 'Global Awareness',
              'Professional and Leadership Development',
              'Special Projects', 'Service to the World',
              'Undergraduate Research']

savestatus="Unsubmitted"
sup_propsub="Proposal Submitted to Supervisor"
sup_propapp="Proposal Approved by Supervisor"
ody_propapp="Proposal Approved by Odyssey Office"
sup_compsub="Completion Form Submitted to Supervisor"
sup_compapp="Completion Form Approved by Supervisor"
ody_compapp="Completion Form Approved by Odyssey Office"
revise="Revision Requested"
rejected="Rejected"

status_dict = {revise:-1, rejected:-2, savestatus:0, sup_propsub:1, sup_propapp:2, ody_propapp:3,
          sup_compsub:4, sup_compapp:5, ody_compapp:6}

WORD_EXTENSION = '.docx'
def viewProposal(request):
    supervisors = User.objects.filter(groups__name='Supervisors')
    return render(request, 'projects/proposal.html', {'supervisors':supervisors,
                                                      'categories':categories})

def status(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    grp = ProjectGroup.objects.filter(project=project)
    return render(request, 'projects/status.html',
                  {'project':project,
                   'statusNum':status_dict.get(project.status),
                   'group':grp})

@login_required(login_url='/odyssey/accounts/login/')
def viewAs(request):
    return render(request, 'projects/viewas.html')

def superLanding(request):
    projects = Project.objects.filter(advisor__username="goadrich")
    proposals = projects.filter(status=sup_propsub)
    completions = projects.filter(status=sup_compsub)
    inprogress = projects.exclude(status=sup_propsub).exclude(status=sup_compsub).exclude(status=ody_compapp)
    appprops = projects.filter(status=sup_propapp)
    appcomps = projects.filter(status=sup_compapp)
    odyprops = projects.filter(status=ody_propapp)
    odycomps = projects.filter(status=ody_compapp)
    groups = ProjectGroup.objects.filter(project__advisor__username="goadrich")
    return render(request, 'projects/superLanding.html', {'projects':projects,
                                                          'props':proposals,
                                                          'comps':completions,
                                                          'completed':odycomps,
                                                          'inprogress':inprogress})

def odyLanding(request):
    projects = Project.objects.exclude(status=savestatus).exclude(status=revise).exclude(status=rejected)
    proposals = projects.filter(status=sup_propapp)
    completions = projects.filter(status=sup_compapp)
    inprogress= projects.exclude(status=sup_propapp).exclude(status=sup_compapp).exclude(status=ody_compapp)
    completed = projects.filter(status=ody_compapp)
    return render(request, 'projects/odysseylanding.html', {'proposals':proposals,
                                                            'completions':completions,
                                                            'inprogress':inprogress,
                                                            'completed':completed})

@csrf_protect
def upload(request):
    if request.method == 'POST':
        logger.debug(request.POST['text'])
        handle_uploaded_file(request.FILES['descfile'])
        return HttpResponseRedirect('success')
    return render(request, 'completion')

def handle_uploaded_file(f):
    with open(f.name, 'wb+') as destination:
        source_stream = StringIO(f.read())
        document = Document(source_stream)
        source_stream.close()
        # for chunk in f.chunks():
        #     destination.write(chunk)
        # handle_word_file(destination, f.name)

def handle_word_file(f, fileName):
    # Convert Docx file to Markdown for storage
    docName = 'clone'+fileName
    document = Document(f)
    document.save(docName)
    output_filename = 'TEST.md'
    md_source = pypandoc.convert(docName, 'md', outputfile= output_filename) # Return this string for now
@csrf_protect
def success(request):
    return render(request, 'projects/success.html')


@csrf_protect
def submitProposal(request):
    now=datetime.date.today()
    if request.method == 'POST':
        if 'narfile' in request.FILES:
            handle_uploaded_file(request.FILES['narfile'])

        data = request.POST
        new_title = data.get('title')
        adv = data.get('super')
        new_adv = User.objects.get(pk=adv)
        new_category = data.get('cat')
        # handle empty date for S&S in jquery
        start = data.get('startdate')
        end = data.get('enddate')
        if start == '':
            start = now
        if end == '':
            end = now
        new_project=Project(title=new_title,
                            category=new_category,
                            advisor=new_adv,
                            status="",
                            start_date=start,
                            end_date=end,
                            update_date=now
                            )
        
        new_project.save()
        createGroup(data, new_project)
        new_prop=Proposal(project_id=new_project,
                          narrative=data.get('narrative'),
                          created_date=now,
                          status="",
                          updated_date=now
                          )
        
        new_prop.save()
        if data.get('propose')=="Save & Submit to Supervisor":
            new_project.status=sup_propsub
            new_prop.status=sup_propsub
            new_project.save()
            new_prop.save()            
            return render(request, 'projects/success.html')
        else:
            new_project.status=savestatus
            new_prop.status=savestatus
            new_project.save()
            new_prop.save()
            return render(request,'projects/proposalSave.html', {'project':new_project, 'categories':categories})

def createGroup(data, project):
    num = data.get('groupsize')
    size= int(num)
    ind = ProjectGroup(student=User.objects.get(username="jepsencr"),
                       project=project)
    ind.save()
    if size > 0:
        for i in range(size):
            mail = data.get('group-'+str(i+1))
            grp = ProjectGroup(student=User.objects.get(email=mail),
                               project=project)
            grp.save()
        
            
@csrf_protect
def submitSavedProposal(request, project_id):
    now=datetime.date.today()
    if request.method == 'POST':
        if 'narfile' in request.FILES:
            handle_uploaded_file(request.FILES['narfile'])
        project = get_object_or_404(Project, pk=project_id)
        proposal = get_object_or_404(Proposal, pk=project_id)
        data = request.POST
        uploaded_file = None
        if 'narfile' in request.FILES:
            uploaded_file = request.FILES['narfile']
            print( type(uploaded_file))

        project.title = data.get('title')
        project.advisor = User.objects.get(pk=data.get('super'))
        project.category = data.get('editcat')
        project.status=""
        project.start_date = data.get('startdate')
        project.end_date = data.get('enddate')
        project.update_date = now
        proposal.narrative=data.get('narrative')
        proposal.updated_date=now
        proposal.status=""
        if data.get('propose')=="Save & Submit to Supervisor":
            project.status=sup_propsub
            proposal.status=sup_propsub
            project.save()
            proposal.save()
            return render(request, 'projects/success.html')
        else:
            project.status=savestatus
            proposal.status=savestatus
            project.save()
            proposal.save()
            return render(request,'projects/proposalSave.html', {'project':project})
                
def editProposal(request, project_id):
    supervisors = User.objects.filter(groups__name='Supervisors')
    project = get_object_or_404(Project, pk=project_id)
    return render(request, 'projects/proposalEdit.html',
                  {'project':project, 'supervisors':supervisors,
                   'categories':categories, 'startdate':project.start_date.isoformat(),
                   'enddate':project.end_date.isoformat()})


def landing(request):
    projects = Project.objects.exclude(status=savestatus).exclude(status=revise).exclude(status=ody_compapp)

    proposals = Proposal.objects.filter(status=savestatus)
    completions = Completion.objects.filter(status=savestatus)
    revprops = Proposal.objects.filter(status=revise)
    revcomps = Completion.objects.filter(status=revise)
    complete = Project.objects.filter(status=ody_compapp)
    return render(request, 'projects/landing.html', {'projects':projects,
                                                     'proposals':proposals,
                                                     'completions':completions,
                                                     'revprops':revprops,
                                                     'revcomps':revcomps})

def viewCompletion(request, project_id):

projects/templates/projects/Status.html
{% extends "projects/base.html" %}
{% block title %}Odyssey Project Status{% endblock %}
{% block header %}{{project.title}}{% endblock %}
{% block content %}


<div class="container-fluid">
	<ul class="timeline" id="timeline">
		{% if statusNum >= 1 %}
		<div id="Completed">
		{% else %}
		<div id="Uncompleted">
		{% endif %}
		<li class="li complete">
			<div class="status">
				<h4>Submitted</h4>
				<h4>Proposal</h4>
			</div>
		</li>
		</div>
		{% if statusNum >= 2 %}
		<div id="Completed">
		{% else %}
		<div id="Uncompleted">
		{% endif %}
		<li class="li complete">
			<div class="status">
				<h4>Approved by:</h4>
				<h4>Supervisor</h4>
			</div>
		</li>
		</div>
		{% if statusNum >= 3 %}
		<div id="Completed">
		{% else %}
		<div id="Uncompleted">
		{% endif %}
		<li class="li complete">
			<div class="status">
				<h4>Approved by:</h4>
				<h4>Odyssey</h4>
			</div>
		</li>
		</div>
		{% if statusNum >= 4 %}
		<div id="Completed">
		{% else %}
		<div id="Uncompleted">
		{% endif %}
		<li class="li complete">
			<div class="status">
				<h4>Submitted</h4>
				<h4>Completion</h4>
			</div>
		</li>
		</div>
		{% if statusNum >= 5 %}
		<div id="Completed">
		{% else %}
		<div id="Uncompleted">
		{% endif %}
		<li class="li complete">
			<div class="status">
				<h4>Approved by:</h4>
				<h4>Supervisor</h4>
			</div>
		</li>
		</div>
		{% if statusNum >= 6 %}
		<div id="Completed">
		{% else %}
		<div id="Uncompleted">
		{% endif %}
		<li class="li complete">
			<div class="status">
				<h4>Approved by:</h4>
				<h4>Odyssey</h4>
			</div>
		</li>
		</div>
	</ul>
</div>
	<div class="body">
		<h3 id="projectCategory">{{project.category}}</h3>
		<div>
			<h4>Status: {{project.status}}</h4>
			<p id="supervisor">Supervisor: <a href="mailto:{{project.advisor.email}}?Subject=Odyssey%20Project: {{project.title}}" target="_top" id="SupEmail">{{project.advisor.last_name}}, {{project.advisor.first_name}}</a>
			</p>
			<p id="group">Group Member(s):</p>
			<p id="startdate">Start Date: {{project.start_date}}</p>
			<p id="enddate">End Date: {{project.end_date}}</p>
			<p><a href="mailto:odyssey@hendrix.edu?Subject=Odyssey%20Project: {{project.title}}" target="_top" id="OdyEmail">Contact the Odyssey Office</a>
			</p>
		</div>
	</div>
	{% if statusNum == 3 %}
	<div class="body">
    <a href="{% url 'projects:completion' project.id %}" class="btn btn-default">Completion Form</a>
    </div>
    
	{% endif %}
{% load static from staticfiles %}

<script src="{% static "projects/timeline.js" %}"></script>

{% endblock %}

projects/templates/projects/completionSave.html
{% extends "projects/base.html" %}
{% block title %}Save Successful{% endblock %}
{% block header %}Success{% endblock %}
{% block content %}
<div class="body">
<p>Your completion form has been saved. Please contact your project supervisor or the Odyssey office with any questions.</p>
<a href="{% url 'projects:editcomp' project.id %}">Continue editing</a>
<br>
<a href="/odyssey/">Return to Odyssey portal</a>
</div>
{% endblock %}

projects/templates/projects/landing.html
{% extends "projects/base.html" %}
{% block header %} Your Hendrix Odyssey {% endblock %}
{% block content %}
<h3>Saved Forms</h3>
<table id="saved_forms_table" class="display">
    <thead>
        <tr>
            <th>Project</th>
            <th>Form Type</th>
            <th>Updated</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
      {% for p in revprops %}
        <tr class="clickableP" id="{{p.project_id.id}}">
            <td><a href="{% url 'projects:edit' p.project_id.id %}">{{p.project_id.title}}</a></td>
            <td>Revised Project Proposal</td>
            <td>{{p.updated_date}}</td>
            <td>
            <div id="icons">
                <a href="{% url 'projects:edit' p.project_id.id %}" class="btn btn-link" aria-label="Edit">
                    <span class="glyphicon glyphicon-edit" aria-hidden="true" id="editicon"></span>
                </a>
                <a href="#" class="btn btn-link" aria-label="Delete">
                  <span class="glyphicon glyphicon-trash" aria-hidden="true" id="delicon"></span>
                </a>
                </div>
            </td>
        </tr>
        {% endfor %}
        {% for p in revcomps %}
        <tr class="clickableP" id="{{p.project_id.id}}">
            <td><a href="{% url 'projects:editcomp' p.project_id.id %}">{{p.project_id.title}}</a></td>
            <td>Revised Project Completion</td>
            <td>{{p.updated_date}}</td>
            <td>
            <div id="icons">
                <a href="{% url 'projects:editcomp' p.project_id.id %}" class="btn btn-link" aria-label="Edit">
                    <span class="glyphicon glyphicon-edit" aria-hidden="true" id="editicon"></span>
                </a>
                <a href="#" class="btn btn-link" aria-label="Delete">
                  <span class="glyphicon glyphicon-trash" aria-hidden="true" id="delicon"></span>
                </a>
                </div>
            </td>
        </tr>
        {% endfor %}
        {% for p in proposals %}
        <tr class="clickableP" id="{{p.project_id.id}}">
            <td><a href="{% url 'projects:edit' p.project_id.id %}">{{p.project_id.title}}</a></td>
            <td>Project Proposal</td>
            <td>{{p.updated_date}}</td>
            <td>
            <div id="icons">
                <a href="{% url 'projects:edit' p.project_id.id %}" class="btn btn-link" aria-label="Edit">
                    <span class="glyphicon glyphicon-edit" aria-hidden="true" id="editicon"></span>
                </a>
                <a href="#" class="btn btn-link" aria-label="Delete">
                	<span class="glyphicon glyphicon-trash" aria-hidden="true" id="delicon"></span>
                </a>
                </div>
            </td>
        </tr>
        {% endfor %}
        {% for c in completions %}
        <tr class="clickableC" id="{{c.project_id.id}}">
            <td><a href="{% url 'projects:editcomp' c.project_id.id %}">{{c.project_id.title}}</a></td>
            <td>Project Completion</td>
            <td>{{c.updated_date}}</td>
            <td>
            <div id="icons">
                <a href="{% url 'projects:editcomp' c.project_id.id %}" class="btn btn-link" aria-label="View">
                    <span class="glyphicon glyphicon-edit" aria-hidden="true" id="editicon"></span>
                </a>
                <a href="#" class="btn btn-link" aria-label="Hide">
                	<span class="glyphicon glyphicon-trash" aria-hidden="true" id="delicon"></span>
                </a>
                </div>
            </td>
        </tr>
        {% endfor %}
    </tbody>

</table>
<h3>In Progress</h3>
<table id="progress_table" class="display">
    <thead>
        <tr>
        <th>Project</th>
        <th>Status</th>
        <th>Update</th>
        <th></th>
        </tr>
    </thead>
    <tbody>
    {% for p in projects %}
        <tr class="clickable" id="{{p.id}}">
          <td><a href="{% url 'projects:status' p.id %}">{{p.title}}</a></td>
          <td>{{p.status}}</td>
          <td>{{ p.update_date }}</td>
          
          <td><div id="icons">
            <a href="{% url 'projects:status' p.id %}" class="btn btn-link" aria-label="View">
            	<span class="glyphicon glyphicon-eye-open" aria-hidden="true" id="viewicon"></span></a>
            <a href="" class="btn btn-link" aria-label="Hide">
                <span class="glyphicon glyphicon-remove" aria-hidden="true" id="hideicon"></span>
            </a></div>
          </td>
          
        </tr>
    {% endfor %}
    </tbody>

</table>
<h3>Completed Projects</h3>
<table id="completion_table" class="display">
    <thead>
        <tr>
            <th>Project</th>
            <th>Category</th>
            <th>Completed</th>
            <th>Supervisor</th>
        </tr>
    </thead>
    <tbody>
        {% for p in completed %}
        <tr class="clickable" id="{{p.id}}">
            <td><a href="{% url 'projects:status' p.id %}">{{p.title}}</a></td>
            <td>{{p.category}}</td>
            <td>{{p.update_date}}</td>
            <td>{{p.advisor.last_name}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% load static from staticfiles %}
<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.11/js/jquery.dataTables.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/buttons/1.1.2/js/dataTables.buttons.min.js"></script>
<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/buttons/1.1.2/js/buttons.colVis.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/t/dt/jq-2.2.0,dt-1.10.11,b-1.1.2,r-2.0.2,se-1.1.2/datatables.min.js"></script>
<script src="{% static 'projects/landing.js' %}"></script>
{% endblock %}

projects/templates/projects/proposalSave.html
{% extends "projects/base.html" %}
{% block title %}Save Successful{% endblock %}
{% block header %}Success{% endblock %}
{% block content %}
<div class="body">
<p>Your project proposal has been saved. Please contact your project supervisor or the Odyssey office with any questions.</p>
<a href="{% url 'projects:edit' project.id %}">Continue editing</a>
<br>
<a href="/odyssey/">Return to Odyssey portal</a>
</div>
{% endblock %}

projects/templates/projects/success.html
{% extends "projects/base.html" %}
{% block title %}Submission Successful{% endblock %}
{% block header %}Success{% endblock %}
{% block content %}
<div class="body">
<p>Your submission was successful. Please contact your project supervisor or the Odyssey office with any questions.</p>
<a href="/odyssey/">Click here to return to your Odyssey portal</a>
</div>
{% endblock %}

projects/templates/projects/superLanding.html
{% extends "projects/base.html" %}
{% block header %} Your Hendrix Odyssey {% endblock %}
{% block content %}
<h3>Awaiting Approval</h3>
    <table id="awaiting_table" class="display">
        <thead>
            <tr>
                <th>Project</th>
                <th>Form Type</th>
                <th>Updated</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for p in props %}
            <tr id="{{p.id}}">
                <td><a href="{% url 'projects:superprop' p.id %}">{{p.title}}</a></td>
                <td>Project Proposal</td>
                <td>{{p.update_date}}</td>
                <td><div id="icons">
                <a href="{% url 'projects:superprop' p.id %}" class="btn btn-link" aria-label="Edit">
                    <span class="glyphicon glyphicon-edit" aria-hidden="true" id="editicon"></span>
                </a>
                <a href="#" class="btn btn-link" aria-label="Delete">
                    <span class="glyphicon glyphicon-trash" aria-hidden="true" id="delicon"></span>
                </a>
                </div>
            </td>
            </tr>
            {% endfor %}
            {% for p in comps %}
            <tr id="{{p.id}}">
                <td><a href="{% url 'projects:supReviewComp' p.id %}">{{p.title}}</a></td>
                <td>Project Completion</td>
                <td>{{p.update_date}}</td>
                <td><div id="icons">
                <a href="{% url 'projects:supReviewComp' p.id %}" class="btn btn-link" aria-label="Edit">
                    <span class="glyphicon glyphicon-edit" aria-hidden="true" id="editicon"></span>
                </a>
                <a href="#" class="btn btn-link" aria-label="Delete">
                    <span class="glyphicon glyphicon-trash" aria-hidden="true" id="delicon"></span>
                </a>
                </div>
            </td>
            </tr>
            {% endfor %}
        </tbody>
        
    </table>
<h3>In Progress</h3>
<table id="progress_table" class="display">
    
    <thead>
        <tr>
            <th>Project</th>
            <th>Status</th>
            <th>Updated</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    {% for p in inprogress %}
        <tr id="{{p.id}}">
            <td><a href="{% url 'projects:superview' p.id %}">{{p.title}}</a></td>
            <td>{{p.status}}</td>
            <td>{{p.update_date}}</td>
            <td><div id="icons">
            <a href="{% url 'projects:superview' p.id %}" class="btn btn-link" aria-label="Edit">
            <span class="glyphicon glyphicon-edit" aria-hidden="true" id="editicon"></span>
            </a>
            <a href="#" class="btn btn-link" aria-label="Delete">
            <span class="glyphicon glyphicon-trash" aria-hidden="true" id="delicon"></span>
            </a>
            </div>
            </td>
        </tr>
    {% endfor %}
    </tbody>
    
</table>
<h3>Completed Projects</h3>
<table id="complete_table" class="display">
    
    <thead>
        <tr>
            <th>Project</th>
            <th>Category</th>
            <th>Completed</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for p in completed %}
        <tr id="{{p.id}}">
            <td>{{p.title}}</td>
            <td>{{p.category}}</td>
            <td>{{p.update_date}}</td>
            <td>
            <div id="icons">
            <a href="#" class="btn btn-link" aria-label="Edit">
            <span class="glyphicon glyphicon-edit" aria-hidden="true" id="editicon"></span>
            </a>
            <a href="#" class="btn btn-link" aria-label="Delete">
            <span class="glyphicon glyphicon-trash" aria-hidden="true" id="delicon"></span>
            </a>
            </div>
            </td>
        </tr>
        {% endfor %}
    </tbody>
    
</table>

{% load static from staticfiles %}
<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.11/js/jquery.dataTables.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/buttons/1.1.2/js/dataTables.buttons.min.js"></script>
<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/buttons/1.1.2/js/buttons.colVis.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/t/dt/jq-2.2.0,dt-1.10.11,b-1.1.2,r-2.0.2,se-1.1.2/datatables.min.js"></script>
<script src="{% static 'projects/superlanding.js' %}"></script>
{% endblock %}